[auth]
username = ""
api_key = ""

[options]
download_favorites = true
safe_mode = false

[query]
tags = [
    "wolf",
    "muscle",
    "solo",
    "femboys_and_firearms",
    "femboy_rimming",
]
artists = [
    "nekoyasha",
    "dogbreath",
    "angiewolfnsfw",
    "angiewolf",
]
pools = [
    12345,
    99887,
]
collections = [
    222,
    444,
]
posts = [
    1883912,
    1723001,
]
